import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<nav className="bg-black border-b border-zinc-800 px-8 py-4 flex justify-between items-center">
  <div className="text-white font-semibold">
    ChainPulse Quant
  </div>
  <div className="space-x-6 text-gray-400">
    <a href="/" className="hover:text-white">Home</a>
    <a href="/app" className="hover:text-white">Dashboard</a>
    <a href="/methodology" className="hover:text-white">Methodology</a>
    <a href="/case-study" className="hover:text-white">Case Study</a>
    <a href="/blog" className="hover:text-white">Blog</a>
  </div>
</nav>
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
